name: lesson_72_permissions
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-321.0.dev

dependencies:
  cloud_firestore: ^5.0.2
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  provider: ^6.1.2
  location: ^7.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
