// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_B2o0k8HUMH4hudwSDCEJbavgsNkBbZ8',
    appId: '1:72869317852:web:fb4bafb08da8fddf08b819',
    messagingSenderId: '72869317852',
    projectId: 'travel-app-8286f',
    authDomain: 'travel-app-8286f.firebaseapp.com',
    storageBucket: 'travel-app-8286f.appspot.com',
    measurementId: 'G-YXY9ZHNGPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6bsInHNmWCeebVA0pFiDJg7sWpbFGblQ',
    appId: '1:72869317852:android:2a096a1ee0c1b57e08b819',
    messagingSenderId: '72869317852',
    projectId: 'travel-app-8286f',
    storageBucket: 'travel-app-8286f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzJsG0iXvesq_NMQ5O_HSBqisYAVn7_M',
    appId: '1:72869317852:ios:47f19a9d3130c2c108b819',
    messagingSenderId: '72869317852',
    projectId: 'travel-app-8286f',
    storageBucket: 'travel-app-8286f.appspot.com',
    iosBundleId: 'com.example.lesson72Permissions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzJsG0iXvesq_NMQ5O_HSBqisYAVn7_M',
    appId: '1:72869317852:ios:47f19a9d3130c2c108b819',
    messagingSenderId: '72869317852',
    projectId: 'travel-app-8286f',
    storageBucket: 'travel-app-8286f.appspot.com',
    iosBundleId: 'com.example.lesson72Permissions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_B2o0k8HUMH4hudwSDCEJbavgsNkBbZ8',
    appId: '1:72869317852:web:09b27d8839cd742a08b819',
    messagingSenderId: '72869317852',
    projectId: 'travel-app-8286f',
    authDomain: 'travel-app-8286f.firebaseapp.com',
    storageBucket: 'travel-app-8286f.appspot.com',
    measurementId: 'G-DGSS8L2R9S',
  );
}
